# Site settings
title: Portfolio
name: Daniel Torres
email: daniel.torrer@gmail.com
url: https://monkeythecoder.github.io/
description: "Projects, ideas and stuff that I'm working on"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  #primary: 00A2D1 #80B3FF
  #secondary: FBB351 #FD6E8A
  #secondary-dark: 2E2E2E #A2122F
  primary: D2043A #80B3FF
  secondary: 8D163D #FD6E8A
  secondary-dark: 2D1336 #A2122F
  bg: 3C1A46 #A2122F
  #text: 18BC9C #A2122F
  text: 1dbda1 #A2122F
  text-link: FFDC00 #A2122F


# Footer settings
footer:
  copyright: Daniel Torres
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/spacem3n
  - title: facebook
    url: https://www.facebook.com/Alex.spoon
  - title: github
    url: https://github.com/monkeythecoder
  - title: linkedin
    url: https://www.linkedin.com/in/danieltorreshdez

# Postal address (add as many lines as necessary)
address:
  - line: Puebla, México 

# Credits content
credits: 'Theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
