# Site settings
title: Portfolio
name: Daniel Torres
email: daniel.torrer@gmail.com
url: https://monkeythecoder.github.io/
description: "Projects, ideas and stuff that I'm working on"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 70B1BA #80B3FF
  secondary: 7A626E #FD6E8A
  secondary-dark: 4D6A6E #A2122F

# Footer settings
footer:
  copyright: Daniel Torres
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/spacem3n
  - title: facebook
    url: https://www.facebook.com/Alex.spoon
  - title: github
    url: https://github.com/monkeythecoder/
  - title: linkedin
    url: https://www.linkedin.com/in/danieltorreshdez

# Postal address (add as many lines as necessary)
address:
  - line: Puebla, México 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
